#VERSION=1.0

version: 2
updates:
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "weekly"
  # - package-ecosystem: "terraform"
  #   directory: "/"
  #   schedule:
  #     interval: "weekly"
  # - package-ecosystem: "docker"
  #   directory: "/"
  #   schedule:
      # interval: "weekly"
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"