repos:
  # Markdown Formatting
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v2.7.1 # Use the sha or tag you want to point at
    hooks:
      - id: prettier
        # types_or: [css, javascript]

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
      - id: detect-private-key
      - id: check-executables-have-shebangs
      - id: check-shebang-scripts-are-executable
      - id: end-of-file-fixer
      - id: trailing-whitespace
  - repo: https://github.com/igorshubovych/markdownlint-cli
    rev: v0.33.0
    hooks:
      - id: markdownlint
