name: Bug report
about: File a bug report
title: '[BUG] <title>'
labels:
  - bug
  - priority:low
  - status:review_needed

---

**Provide all relevant information below, e.g. OS version, language versions.**

examples:
  - **OS:** macOS 14
  - **python version:** 3.11.0
  - **npm version:** 7.20.0
  - **terraform version:** 1.0.0
  - **serverless version:** 2.0.0
