name: Issue assignment

on:
    issues:
        types: [opened, labeled]

jobs:
  auto-assign:
    if: github.event.label.name == 'status:review_needed'
    runs-on: ubuntu-latest
    steps:
      - name: 'Auto-assign issue'
        uses: pozil/auto-assign-issue@v1
        with:
          assignees: mrc0der
          numOfAssignee: 1
          allowSelfAssign: true